### ISSUE TITLE
[Question] on Reanimated declaration

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#133]
I've built an animation with reanimated that works great:

```

function runSpring(clock, value, dest) {
  const state = {
    finished: new Value(0),
    velocity: new Value(0),
    position: new Value(0),
    time: new Value(0),
  };

  const config = {
    damping: 20,
    mass: 1,
    stiffness: 100,
    overshootClamping: false,
    restSpeedThreshold: 0.001,
    restDisplacementThreshold: 0.001,
    toValue: new Value(0),
  };

  return [
    cond(clockRunning(clock), 0, [
      set(state.finished, 0),
      set(state.velocity, 0),
      set(state.position, value),
      set(config.toValue, dest),
      startClock(clock),
    ]),
    spring(clock, state, config),
    cond(state.finished, stopClock(clock)),
    state.position,
  ];
}

    this.translateY = cond(
      eq(gestureState, State.END),
      [
        set(translationY, runSpring(clockY, translationY, 0)),
        translationY,
      ],
      translationY,
    );
```

Where `translationX` comes from an `event()` handler.  Why can't I write:

```
    this.translateY = cond(
      eq(gestureState, State.END),
      runSpring(clockY, translationY, 0),
      translationY,
    );
```

The second code snippet doesn't produce the excepted behavior. I'm still quite new with this library.

**Comment by enesTufekci** [comment]
Can you also post or give link to the `runSpring` function used here?

**Comment by wcandillon** [comment]
Thanks! I edited the post above, I think I'm still misunderstanding and misusing reanimated programming model.

**Comment by saleksandras** [comment]
@wcandillon I believe you need to assign `state.position` to `value` argument in your `runSpring` function instead of just returning it.

```
function runSpring(clock, value, dest) {
  ...
  return [
    ...
    cond(state.finished, stopClock(clock)),
    set(value, state.position)
  ];
}
```

BTW Love your "Can it be done in React Native?" videos!

**Comment by kirkness** [comment]
Looks like I'm trying to figure out the same thing, did you find a solution? I'm trying to snap a card with a spring back to its original position. Created a gist [here](https://gist.github.com/kirkness/4a0003dedb60bf80217c55a0950b77a3).

Essentially, after snapping when the spring node is re-evaluated, the card jumps around the screen. I think its because the second spring finishes at a differnent time (works with `timing()`).

Is there a recommended way of translating an x + y value when drag ends. Feels like this problem im facing relates to handling the 2 values separately and running 2 springs/clocks.
